### ISSUE TITLE
Bug for s_o=2 operator.

### ISSUE THREAD

**Issue by georgebisbas** [devitocodes/devito#1060]
EDIT:UPDATE-----

A space order 2 operator triggers compilation error. Initially emerged from benchmarking elastic_example.py . 
An MFE created for this issue:

```
import numpy as np
from devito import Grid, Eq, Operator
from devito import div, grad
from devito import VectorTimeFunction, TensorTimeFunction
# Parameters
shape = (50, 50, 50)
spacing = (10.0, 10.0, 10.0)
tn = 50.0
space_order = 2
# Grid
grid = Grid(shape=shape, dtype=np.float32)
# Functions
v = VectorTimeFunction(name='v', grid=grid, space_order=space_order)
tau = TensorTimeFunction(name='tau', grid=grid, space_order=space_order)
# Equations
u_v = Eq(v.forward, div(tau))
u_t = Eq(tau.forward, grad(v.forward))
# Operator
op = Operator([u_v] + [u_t])
# summary = op.apply()
```

Issue first uncovered:

Probably after targets introduction the benchmarking of elastic and viscoelastic problems is breaking.
TO reproduce the issue, a devitobench installation is needed.
Run:

python `benchmarks/user/benchmark.py run -P elastic`

Luckily emerged at the first local tries of testing benchmarking. Another case that marks the need for benchmark testing as important.

**Comment by georgebisbas** [comment]
Log:
```
(devito) gb4018@gb4018-XPS-13-9365:~/workspace/devitocodes/devito$ python benchmarks/user/benchmark.py test -P elastic -d 100 100 100
Traceback (most recent call last):
  File "/home/gb4018/workspace/devitocodes/devito/devito/tools/memoization.py", line 89, in __call__
    res = cache[key]
KeyError: (<function ElasticWaveSolver.op_fwd at 0x7f73762b18c0>, (None,), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gb4018/workspace/devitocodes/devito/devito/targets/common/engine.py", line 121, in wrapper
    graph, = args
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmarks/user/benchmark.py", line 491, in <module>
    benchmark()
  File "/home/gb4018/anaconda3/envs/devito/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/gb4018/anaconda3/envs/devito/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/gb4018/anaconda3/envs/devito/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gb4018/anaconda3/envs/devito/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gb4018/anaconda3/envs/devito/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "benchmarks/user/benchmark.py", line 216, in cli_test
    test(problem, **kwargs)
  File "benchmarks/user/benchmark.py", line 229, in test
    _, _, _, res = run(**kwargs)
  File "/home/gb4018/workspace/devitocodes/devito/examples/seismic/elastic/elastic_example.py", line 44, in run
    rec1, rec2, v, tau, summary = solver.forward(autotune=autotune)
  File "/home/gb4018/workspace/devitocodes/devito/examples/seismic/elastic/wavesolver.py", line 95, in forward
    summary = self.op_fwd(save).apply(src=src, rec1=rec1, lam=lam, mu=mu, irho=irho,
  File "/home/gb4018/workspace/devitocodes/devito/devito/tools/memoization.py", line 91, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/home/gb4018/workspace/devitocodes/devito/examples/seismic/elastic/wavesolver.py", line 38, in op_fwd
    space_order=self.space_order, **self._kwargs)
  File "/home/gb4018/workspace/devitocodes/devito/examples/seismic/elastic/operators.py", line 66, in ForwardOperator
    op = Operator([u_v] + [u_t] + srcrec, subs=model.spacing_map, name="ForwardElastic")
  File "/home/gb4018/workspace/devitocodes/devito/devito/backends.py", line 73, in __call__
    return t(*args, **kwargs)
  File "/home/gb4018/workspace/devitocodes/devito/devito/operator/operator.py", line 136, in __new__
    op = cls._build(expressions, **kwargs)
  File "/home/gb4018/workspace/devitocodes/devito/devito/operator/operator.py", line 178, in _build
    op, target_state = cls._specialize_iet(op, **kwargs)
  File "/home/gb4018/workspace/devitocodes/devito/devito/operator/operator.py", line 312, in _specialize_iet
    return iet_lower(iet, *set_dle_mode(dle))
  File "/home/gb4018/workspace/devitocodes/devito/devito/targets/basic.py", line 151, in iet_lower
    graph = rewriter.process(iet)
  File "/home/gb4018/workspace/devitocodes/devito/devito/targets/basic.py", line 28, in process
    self._pipeline(graph)
  File "/home/gb4018/workspace/devitocodes/devito/devito/targets/cpu.py", line 54, in _pipeline
    self.ompizer.make_simd(graph, simd_reg_size=self.platform.simd_reg_size)
  File "/home/gb4018/workspace/devitocodes/devito/devito/targets/common/engine.py", line 126, in wrapper
    maybe_timed(graph.apply, func.__name__)(partial(func, self), **kwargs)
  File "/home/gb4018/workspace/devitocodes/devito/devito/tools/decorators.py", line 122, in __call__
    retval = self.func(*args, **kwargs)
  File "/home/gb4018/workspace/devitocodes/devito/devito/targets/common/engine.py", line 66, in apply
    dag = self._create_call_graph()
  File "/home/gb4018/workspace/devitocodes/devito/devito/targets/common/engine.py", line 58, in _create_call_graph
    assert dag.size == len(self.efuncs)
AssertionError

```

**Comment by FabioLuporini** [comment]
could you also try on top of #1030 ?

**Comment by georgebisbas** [comment]
> could you also try on top of #1030 ?

Sure, I will try.

**Comment by georgebisbas** [comment]
The same error is taking place on top of #1030. 
Can you run
`python benchmarks/user/benchmark.py run -P elastic`
to confirm ?

**Comment by FabioLuporini** [comment]
so this one works right?

https://github.com/devitocodes/devito/blob/master/.travis.yml#L132

@mloubout @rhodrin this is a symptom we may not be properly testing elastic (or, IOW, be missing some suitable regression tests)

**Comment by georgebisbas** [comment]
elastic itself runs fine. Elastic under benchmarking is not fine.

**Comment by FabioLuporini** [comment]
right. So what's the difference between these two?

**Comment by georgebisbas** [comment]
The benchmarking one runs with `blockinner=True`. I guess that has changed over the latest PRs?
Parameters like shape, tn etc... are almost the same...

**Comment by FabioLuporini** [comment]
does it work with blockinner=False ?

**Comment by georgebisbas** [comment]
I tried but it wouldn't change the configuration. Like. So there must be an issue in the config somewhere. I am afraid I cannot allocate more time today on this so I will load it to the next week.

**Comment by georgebisbas** [comment]
> does it work with blockinner=False ?

It doesn;t work either.

**Comment by georgebisbas** [comment]
After discussion with @mloubout and @FabioLuporini issue emerges with so=2.

`python examples/seismic/elastic/elastic_example.py -so 2` fails

**Comment by georgebisbas** [comment]
Error Log:
```
DSE: flops: 17 >> 14 (elapsed 0.01 s)
     flops: 34 >> 25 (elapsed 0.01 s)
     flops: 5 >> 4 (elapsed 0.00 s)
     flops: 15 >> 11 (elapsed 0.01 s)
     flops: 10 >> 7 (elapsed 0.01 s)
     [Total elapsed: 0.04 s]
Traceback (most recent call last):
  File "/home/gb4018/devitocodes/devito/devito/targets/common/engine.py", line 123, in wrapper
    graph, = args
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/seismic/elastic/mfe_2.py", line 39, in <module>
    op = Operator([u_v] + [u_t])
  File "/home/gb4018/devitocodes/devito/devito/backends.py", line 73, in __call__
    return t(*args, **kwargs)
  File "/home/gb4018/devitocodes/devito/devito/operator/operator.py", line 136, in __new__
    op = cls._build(expressions, **kwargs)
  File "/home/gb4018/devitocodes/devito/devito/operator/operator.py", line 178, in _build
    op, target_state = cls._specialize_iet(op, **kwargs)
  File "/home/gb4018/devitocodes/devito/devito/operator/operator.py", line 312, in _specialize_iet
    return iet_lower(iet, *set_dle_mode(dle))
  File "/home/gb4018/devitocodes/devito/devito/targets/basic.py", line 151, in iet_lower
    graph = rewriter.process(iet)
  File "/home/gb4018/devitocodes/devito/devito/targets/basic.py", line 28, in process
    self._pipeline(graph)
  File "/home/gb4018/devitocodes/devito/devito/targets/cpu.py", line 54, in _pipeline
    self.ompizer.make_simd(graph, simd_reg_size=self.platform.simd_reg_size)
  File "/home/gb4018/devitocodes/devito/devito/targets/common/engine.py", line 128, in wrapper
    maybe_timed(graph.apply, func.__name__)(partial(func, self), **kwargs)
  File "/home/gb4018/devitocodes/devito/devito/tools/decorators.py", line 122, in __call__
    retval = self.func(*args, **kwargs)
  File "/home/gb4018/devitocodes/devito/devito/targets/common/engine.py", line 67, in apply
    dag = self._create_call_graph()
  File "/home/gb4018/devitocodes/devito/devito/targets/common/engine.py", line 59, in _create_call_graph
    assert dag.size == len(self.efuncs)
AssertionError

```
