### ISSUE TITLE
Running MPI with DEVITO_MPI=0 , missing attribute data

### ISSUE THREAD

**Issue by jrt54** [devitocodes/devito#1255]
I'm trying to run MPI on a python script where each rank calls Devito operations to forward-model a single shot. So I want Devito to run without any awareness of MPI but I'm calling the script with MPI to parallelize the I/O across several shots.  Here's my minimal reproducible (hopefully) example 

So before running this I have set DEVITO_MPI=0 as an environment variable. 

"mpirun -np 2 python test.py" (note this works if I run mpirun -np 1)

Here's "test.py":
```

from mpi4py import MPI
from devito import Grid, Function, configuration



grid=Grid(shape=(10,10,10), extent=(100,100,100), comm=None)
vel=Function(name="vel", grid=grid, space_order=2)
vel.data[:]=1.0

print("All done")
```

I get this error printed twice. 

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    vel.data[:]=1.0
  File "/root/devito-cpu/devito-src/devito/devito/finite_differences/differentiable.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (self.__class__, name))

Notes: It works (although not as I intend) if I set DEVITO_MPI=1. I'm not getting an error if I try to access the "data" attribute of SparseTimeFunction objects.

**Comment by jrt54** [comment]
Update: it looks like you can workaround this by setting DEVITO_MPI=1 AND initializing my grid with comm=MPI.COMM_SELF. Doing so is now giving me the expected behavior. 

Not sure if this is expected behavior, but comm=None (as in the example above) does not work, and similarly I can't unset DEVITO_MPI (or set it to 0) while running with more than one rank.

**Comment by FabioLuporini** [comment]
I've added this to my TODO list. Thanks for reporting

**Comment by georgebisbas** [comment]
Hi @jrt54, this seems to be resolved now.
Unless you have any objections maybe we can close this issue.

**Comment by AMzaheri** [comment]
Hello,

I'm trying to parallelise an inversion code over the shots. The python code works serially. But when I parallelise it using mpi4py, the same error as  jrt54 occurs. Setting DEVITO_MPI to 1 or 0 creates some new errors. as follows:

![image](https://user-images.githubusercontent.com/3063907/218781580-8628171a-ad98-44b7-b8a2-f7d6e3a45fb9.png)

![image](https://user-images.githubusercontent.com/3063907/218781678-aac4fe82-eef2-4ce9-a333-8f220effb1fe.png)

Any idea how I could solve this?
Thank you,
