### ISSUE TITLE
PEP 3118 buffer format string

### ISSUE THREAD

**Issue by PAULGOYES** [devitocodes/devito#1730]
I am running the next code: 

```
import numpy as np
import matplotlib.pyplot as plt

from examples.seismic import Model, plot_velocity

# Define a velocity model. The velocity is in km/s
vp = np.zeros((101, 101))
vp[:, :51] = 1.5
vp[:, 51:] = 2.5


#create model class
model = Model(vp=vp,             # A velocity model.
              origin=(0, 0),     # Top left corner.
              shape=(101, 101),  # Number of grid points.
              spacing=(10, 10),  # Grid spacing in m.
              nbpml=40)          # boundary layer.

plot_velocity(model)
```

and I got the next message: 

```
Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.6/site-packages/numpy/core/_internal.py", line 562, in _dtype_from_pep3118
    dtype, align = __dtype_from_pep3118(stream, is_subdtype=False)
  File "/home/paul/.local/lib/python3.6/site-packages/numpy/core/_internal.py", line 639, in __dtype_from_pep3118
    raise ValueError("Unknown PEP 3118 data type specifier %r" % stream.s)
ValueError: Unknown PEP 3118 data type specifier 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fm.py", line 27, in <module>
    nbpml=40)          # boundary layer.
  File "/home/paul/Documents/seismicmodeling/goyes/seismic/model.py", line 322, in __init__
    self.vp = vp
  File "/home/paul/Documents/seismicmodeling/goyes/seismic/model.py", line 450, in vp
    self.m.data[:] = self.pad(1 / (self.vp * self.vp))
  File "/home/paul/devito/devito/function.py", line 258, in data
    self._allocate_memory()
  File "/home/paul/devito/devito/function.py", line 247, in _allocate_memory
    self._data_object = CMemory(self.shape, dtype=self.dtype)
  File "/home/paul/devito/devito/memory.py", line 24, in __init__
    self.ndpointer, self.data_pointer = malloc_aligned(shape, alignment, dtype)
  File "/home/paul/devito/devito/memory.py", line 66, in malloc_aligned
    pointer = np.ctypeslib.as_array(data_pointer, shape=shape)
  File "/home/paul/.local/lib/python3.6/site-packages/numpy/ctypeslib.py", line 521, in as_array
    return array(obj, copy=False)
ValueError: '<P' is not a valid PEP 3118 buffer format string
Exception ignored in: <bound method CMemory.__del__ of <devito.memory.CMemory object at 0x7f0cf7eb3be0>>
Traceback (most recent call last):
  File "/home/paul/devito/devito/memory.py", line 27, in __del__
    free(self.data_pointer)
AttributeError: 'CMemory' object has no attribute 'data_pointer'
```

can you advise me please how can I fix this problem. Thanks.

**Comment by mloubout** [comment]
What version of numpy do you have?

**Comment by PAULGOYES** [comment]
> What version of numpy do you have?

numpy                         1.19.5

I have tried in COLAB, but still I have the same error
https://colab.research.google.com/drive/1X5Ks7ge8JHOfoCStNtf1u7Ne1RUk0AUH?usp=sharing

```
/content/devito/devito/memory.py in <module>()
     10 
     11 from devito.logger import error
---> 12 from devito.tools import numpy_to_ctypes
     13 import devito
     14 

ImportError: cannot import name 'numpy_to_ctypes' from 'devito.tools' (/root/.local/lib/python3.7/site-packages/devito/tools/__init__.py)
```

**Comment by mloubout** [comment]
The log shows that you have two different version of Devito installed. One in `content` (3.1.0 which is older) and one in `site-packagea` that are not compatible (the are over 2 years apart)

**Comment by PAULGOYES** [comment]
@mloubout but in my computer I just installed devito first time. How can I check the logs in my computer ? Because It seem to be the same problem.

**Comment by PAULGOYES** [comment]
I got the result, by installing the last version. Thanks, please close the issue

![image](https://user-images.githubusercontent.com/25279107/127711806-6ca38aa3-9d71-4ec6-a64f-b771cee1d7a1.png)
