### ISSUE TITLE
`ConditionalDimension` with time, x, y, z dimensions raises `AttributeError: 'NullInterval' object has no attribute 'offsets'`

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1753]
The following mfe:
```
from devito import Grid, TimeFunction, Eq, Operator, \
    Function, ConditionalDimension, Le

# Define a physical size
shape = (101, 101, 101)
extent = (1000., 1000., 1000.)

grid = Grid(shape=shape, extent=extent)

x, y, z = grid.dimensions

p = TimeFunction(name='p', grid=grid)

ax_x = Function(name='ax_x', grid=grid)

ax_x.data[:, :, 50] = 1

second_update = Le(ax_x, 1)

# Conditional masks for update
use_2nd = ConditionalDimension(name='use_2nd', parent=z,
                               condition=second_update)

eq_p = Eq(p.forward, 1, implicit_dims=use_2nd)

op = Operator([eq_p])
```
results in this traceback
```
Traceback (most recent call last):
  File "conditionaldimension_mfe.py", line 26, in <module>
    op = Operator([eq_p])
  File "/home/ed/devito/devito/operator/operator.py", line 157, in __new__
    op = cls._build(expressions, **kwargs)
  File "/home/ed/devito/devito/operator/operator.py", line 187, in _build
    stree = cls._lower_stree(clusters, **kwargs)
  File "/home/ed/devito/devito/tools/timing.py", line 76, in __call__
    retval = self.func(*args, **kwargs)
  File "/home/ed/devito/devito/operator/operator.py", line 345, in _lower_stree
    stree = stree_build(clusters)
  File "/home/ed/devito/devito/ir/stree/algorithms.py", line 24, in stree_build
    stree = stree_make_halo(stree)
  File "/home/ed/devito/devito/ir/stree/algorithms.py", line 110, in stree_make_halo
    halo_schemes[n] = HaloScheme(n.exprs, n.ispace)
  File "/home/ed/devito/devito/mpi/halo_scheme.py", line 67, in __init__
    self._mapper = frozendict(classify(exprs, ispace))
  File "/home/ed/devito/devito/mpi/halo_scheme.py", line 366, in classify
    thl, thr = i.touched_halo(d)
  File "/home/ed/devito/devito/ir/support/basic.py", line 375, in touched_halo
    m, M = self.intervals[d].offsets
AttributeError: 'NullInterval' object has no attribute 'offsets'
```
However, in two dimensions + time:
```
from devito import Grid, TimeFunction, Eq, Operator, \
    Function, ConditionalDimension, Le

# Define a physical size
shape = (101, 101)
extent = (1000., 1000.)

grid = Grid(shape=shape, extent=extent)

x, y= grid.dimensions

p = TimeFunction(name='p', grid=grid)

ax_x = Function(name='ax_x', grid=grid)

ax_x.data[:, 50] = 1

second_update = Le(ax_x, 1)

# Conditional masks for update
use_2nd = ConditionalDimension(name='use_2nd', parent=y,
                               condition=second_update)

eq_p = Eq(p.forward, 1, implicit_dims=use_2nd)

op = Operator([eq_p])
```
this error is not raised. Additonally, modifying the mask `Function` to use `shape` and `dimensions` rather than grid doesn't throw the error, nor does replacing `p` with a `Function`

**Comment by EdCaunt** [comment]
Appears similar to #1272

**Comment by georgebisbas** [comment]
This issue seems to be fixed now. I suspect one of the PRs from @FabioLuporini (accidentally) fixed it. @EdCaunt can you confirm?

**Comment by FabioLuporini** [comment]
can you anyway PR the MFE ? to be added to `test_dimension.py::TestConditionalDimension`. docstring should contain an explicit reference to this issue. Test name also could be as simple as test_issue_1753
