### ISSUE TITLE
Fix boolean masking on function data

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1788]
Currently the following mfe throws an error:

```
import numpy as np
from devito import Grid, Function

shape = (5,)
extent = (6)

grid = Grid(shape=shape, extent=extent)

f = Function(name='f', grid=grid)

bool_arr = np.array([True, True, False, False, True])

f.data[bool_arr] = 1

print(f.data)
```

It should return [1, 1, 0, 0, 1], but instead you get the following traceback:
```
Traceback (most recent call last):
  File "/home/ed/Documents/FD_Code/mfes/function_data_boolean_indexing_mfe.py", line 13, in <module>
    f.data[bool_arr] = 1
  File "/home/ed/devito/devito/data/data.py", line 176, in wrapper
    return func(data, *args, **kwargs)
  File "/home/ed/devito/devito/data/data.py", line 263, in __setitem__
    loc_idx = self._index_glb_to_loc(glb_idx)
  File "/home/ed/devito/devito/data/data.py", line 435, in _index_glb_to_loc
    if NONLOCAL in loc_idx:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by EdCaunt** [comment]
Appears this is an issue in 3.9 only
