### ISSUE TITLE
sympy attributeError: 'int' object has no attribute 'is_Mul'

### ISSUE THREAD

**Issue by AMzaheri** [devitocodes/devito#1973]
Hello,

I've been trying to implement adjoint modeling example ( https://slimgroup.github.io/Devito-Examples/tutorials/TLE_Adjoint/), but I encountered the following error:

Traceback (most recent call last):
  File "~/adjoint_example.py", line 48, in <module>
    stencil_v = Eq(v.backward, solve(pde, v.backward)[0])
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1038, in solve
    if fi.is_constant():
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/core/expr.py", line 628, in is_constant
    expr = expr.simplify()
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/core/basic.py", line 1763, in simplify
    return simplify(self, **kwargs)
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/simplify/simplify.py", line 746, in simplify
    expr = short.xreplace(hollow_mul)
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/core/basic.py", line 1183, in xreplace
    value, _ = self._xreplace(rule)
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/core/basic.py", line 1198, in _xreplace
    a_xr = _xreplace(rule)
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/core/basic.py", line 1198, in _xreplace
    a_xr = _xreplace(rule)
  File "~/local/devito/devito/finite_differences/derivative.py", line 225, in _xreplace
    return self._new_from_self(subs=subs), True
  File "~/local/devito/devito/finite_differences/derivative.py", line 202, in _new_from_self
    return Derivative(expr, *self.dims, **_kwargs)
  File "~/local/devito/devito/finite_differences/derivative.py", line 107, in __new__
    obj._ppsubs = as_tuple(frozendict(i) for i in kwargs.get("subs", []))
  File "~/local/devito/devito/tools/utils.py", line 49, in as_tuple
    t = tuple(item)
  File "~/local/devito/devito/finite_differences/derivative.py", line 107, in <genexpr>
    obj._ppsubs = as_tuple(frozendict(i) for i in kwargs.get("subs", []))
  File "~/local/devito/devito/tools/data_structures.py", line 456, in __init__
    self._dict = self.dict_cls(*args, **kwargs)
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/core/rules.py", line 57, in __getitem__
    if self._filter(key):
  File "~/.conda/envs/devito/lib/python3.10/site-packages/sympy/simplify/simplify.py", line 741, in <lambda>
    x.is_Mul and
AttributeError: 'int' object has no attribute 'is_Mul'

I was wondering if you had any idea how to solve this problem.
Thank you,

**Comment by FabioLuporini** [comment]
You're probably using a non-symbolic object somewhere where a symbolic object is instead expected (devito should have probably errored out earlier, but it's not happening...)

We'll need a minimal failing example. Could you follow the instructions https://github.com/devitocodes/devito/wiki/FAQ#how-do-i-find-the-source-of-my-bug-quickly-and-get-support and produce one?

**Comment by AMzaheri** [comment]
Thank you very much for your prompt response. Please see the attached file for a MFE.
Thank you,

**Comment by AMzaheri** [comment]
[MFE.zip](https://github.com/devitocodes/devito/files/9182831/MFE.zip)

**Comment by FabioLuporini** [comment]
ah OK, I see. It has to be

```
from devito import solve
```

not

```
from sympy import solve
```

Can you try again with this change? If it works, I'll close the issue, but please let me know

**Comment by AMzaheri** [comment]
Thank you. Using devito solve the following error was created:

Traceback (most recent call last):
  File "~/adjoint.py", line 40, in <module>
    stencil_v = Eq(v.backward, solve(pde, v.backward)[0])
TypeError: 'Mul' object is not subscriptable

**Comment by FabioLuporini** [comment]
that's probably another issue in your script, can you try removing the `[0]`

**Comment by AMzaheri** [comment]
Great! It works now. Thank you very much.
Best regards,
