### ISSUE TITLE
local_indices errors with SparseFunctions and SparseTimeFunctions running with MPI and 1 point

### ISSUE THREAD

**Issue by deckerla** [devitocodes/devito#2003]
call this script example.py
(this behavior also holds for `SparseTimeFunctions`)
```
import devito
grd = devito.Grid(shape=(4,5))
f = devito.Function(name="f", grid=grd)
sf = devito.SparseFunction(name="sf", grid=grd, npoint=1)
print(sf.local_indices)
```
if I run 
`DEVITO_MPI=1 mpirun -n 2 python example.py`
it errors with
```
(slice(0, 1, None),)
Traceback (most recent call last):
  File "/home/cvx/.julia/dev/Devito/ex.py", line 5, in <module>
    print(sf.local_indices)
  File "/home/cvx/.conda/envs/conda_jl/lib/python3.10/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/cvx/.conda/envs/conda_jl/lib/python3.10/site-packages/devito/types/dense.py", line 643, in local_indices
    return tuple(self._distributor.glb_slices.get(d, slice(0, s))
  File "/home/cvx/.conda/envs/conda_jl/lib/python3.10/site-packages/devito/types/dense.py", line 643, in <genexpr>
    return tuple(self._distributor.glb_slices.get(d, slice(0, s))
  File "/home/cvx/.conda/envs/conda_jl/lib/python3.10/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/cvx/.conda/envs/conda_jl/lib/python3.10/site-packages/devito/mpi/distributed.py", line 116, in glb_slices
    return {d: slice(min(i), max(i) + 1)
  File "/home/cvx/.conda/envs/conda_jl/lib/python3.10/site-packages/devito/mpi/distributed.py", line 116, in <dictcomp>
    return {d: slice(min(i), max(i) + 1)
ValueError: min() arg is an empty sequence
```
At least for the purposes of Devito.jl we would love for it to return a tuple  `(0:-1,)` for ranks where the sparsefunction memory isn't allocated.

**Comment by FabioLuporini** [comment]
@deckerla this is what your PR has fixed right Luke? can we close it?

**Comment by mloubout** [comment]
Yes it is, PR was saying close instead of fix so didn't auto close. closing
