### ISSUE TITLE
Running MPI with Devito fails 

### ISSUE THREAD

**Issue by AMzaheri** [devitocodes/devito#2066]
Hello,

I'm running mpi on a python script where I use devito for forward modelling. I need MPI  and Devito running independent of each other. My problem is similar to [1255 issue](https://github.com/devitocodes/devito/issues/1255).  But their solution doesn't work for me. I set DEVITO_MPI variable to 1 and 0 using export DEVITO_MPI=1, but it creates more errors. The initial error, before setting DEVITO_MPI to 1 or zero is as follows:

Traceback (most recent call last):
 
    with MPIReduction(f, op=dv.mpi.MPI.MAX) as mr:
  File "~/local/devito/devito/builtins/utils.py", line 35, in __enter__
    model = Model(vp=Vp, origin=inpara.origin, shape=inpara.shape, spacing=inpara.spacing,
  File "~/local/devito/examples/seismic/model.py", line 271, in __init__
    self.n.data[0] = 0
  File "~/devito/devito/finite_differences/differentiable.py", line 150, in __getattr__
    super(SeismicModel, self).__init__(origin, spacing, shape, space_order, nbl,
  File "~/local/devito/examples/seismic/model.py", line 124, in __init__
    self._initialize_bcs(bcs=bcs)
  File "~/local/devito/examples/seismic/model.py", line 140, in _initialize_bcs
    raise AttributeError("%r object has no attribute %r" % (self.__class__, name))
    (bcs == "damp" and mmax(self.damp) == 1))
  File "~/local/devito/devito/builtins/arithmetic.py", line 179, in mmax
    with MPIReduction(f, op=dv.mpi.MPI.MAX) as mr:
  File "~/local/devito/devito/builtins/utils.py", line 35, in __enter__
AttributeError: n object has no attribute 'data'. Did you mean: '_data'?
    self.n.data[0] = 0
  File "~/local/devito/devito/finite_differences/differentiable.py", line 150, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (self.__class__, name))
AttributeError: n object has no attribute 'data'. Did you mean: '_data'?

#----------------------------------------
When I run the parallel code with one processor it works. But if I increase the numbers the above error appears.
I'm using mpi4py.

Any idea how I could fix this problem?

Thank you,

**Comment by mloubout** [comment]
What version of devito are you using?
