### ISSUE TITLE
Too many Functions causes Operator compilation to fail

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#2082]
The following:
```
import devito as dv

grid = dv.Grid(shape=(11, 11), extent=(10., 10.))
fs = [dv.Function(name='f_'+str(i), grid=grid)
      for i in range(1019)]  # 1018 works
g = dv.Function(name='g', grid=grid)

eq = dv.Eq(g, sum(fs))
dv.Operator(eq)()
```
fails with this traceback:
```
Traceback (most recent call last):
  File "lots_of_funcs_mfe.py", line 9, in <module>
    dv.Operator(eq)()
  File "/home/ed/devito/devito/operator/operator.py", line 737, in __call__
    return self.apply(**kwargs)
  File "/home/ed/devito/devito/operator/operator.py", line 810, in apply
    cfunction(*arg_values)
ctypes.ArgumentError: too many arguments (1025), maximum is 1024
```

**Comment by mloubout** [comment]
https://github.com/python/cpython/commit/a285af7e626d1b81cf09f8b2bf7656f100bc1237

**Comment by EdCaunt** [comment]
Stems from an inefficiency in my code which I'll need to have a think about given that this limitation seems to be pretty fundamental

**Comment by FabioLuporini** [comment]
why not an extra dimension?

**Comment by FabioLuporini** [comment]
can we close?

**Comment by EdCaunt** [comment]
Sure
